# Programming assignment 8

## 1.	Write a Python Program to Add Two Matrices?

In [8]:
import numpy as np
  
R1 = int(input("Enter the number of rows of matrix 1: "))
C1 = int(input("Enter the number of columns of matrix 1: "))
R2 = int(input("Enter the number of rows of matrix 2: "))
C2 = int(input("Enter the number of columns of matrix 2: "))

print("Enter the entries in a single line (separated by space): ")

entries1 = list(map(int, input().split()))
matrix1 = np.array(entries1).reshape(R1, C1)
print(matrix1)

entries2 = list(map(int, input().split()))
matrix2 = np.array(entries2).reshape(R2, C2)
print(matrix2)

if ((R1==R2) and (C1==C2)):
    result1 = [[0]*C1]*R1
    result = np.array(result1).reshape(R1,C1)
#     print(result)
    for i in range(len(matrix1)):
        for j in range(len(matrix1[0])):
            result[i][j] = matrix1[i][j] + matrix2[i][j]
print('Sum of the matrices are:- ')
print(result)

Enter the number of rows of matrix 1: 3
Enter the number of columns of matrix 1: 3
Enter the number of rows of matrix 2: 3
Enter the number of columns of matrix 2: 3
Enter the entries in a single line (separated by space): 
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
10 11 12 13 14 15 16 17 18
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Sum of the matrices are:- 
[[11 13 15]
 [17 19 21]
 [23 25 27]]


## 2.	Write a Python Program to Multiply Two Matrices?

In [10]:
import numpy as np
  
R1 = int(input("Enter the number of rows of matrix 1: "))
C1 = int(input("Enter the number of columns of matrix 1: "))
R2 = int(input("Enter the number of rows of matrix 2: "))
C2 = int(input("Enter the number of columns of matrix 2: "))

print("Enter the entries in a single line (separated by space): ")

entries1 = list(map(int, input().split()))
matrix1 = np.array(entries1).reshape(R1, C1)
print(matrix1)

entries2 = list(map(int, input().split()))
matrix2 = np.array(entries2).reshape(R2, C2)
print(matrix2)

if (C1==R2):
    result1 = [[0]*C2]*R1
    result = np.array(result1).reshape(R1,C2)
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
print(result)

Enter the number of rows of matrix 1: 3
Enter the number of columns of matrix 1: 3
Enter the number of rows of matrix 2: 3
Enter the number of columns of matrix 2: 3
Enter the entries in a single line (separated by space): 
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
10 11 12 13 14 15 16 17 18
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


## 3.	Write a Python Program to Transpose a Matrix?

In [14]:
import numpy as np
  
R1 = int(input("Enter the number of rows of matrix 1: "))
C1 = int(input("Enter the number of columns of matrix 1: "))

print("Enter the entries in a single line (separated by space): ")

entries1 = list(map(int, input().split()))
matrix = np.array(entries1).reshape(R1, C1)
print(matrix)

result1 = [[0]*R1]*C1
result = np.array(result1).reshape(C1,R1)

for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        result[j][i] = matrix[i][j]
print(result)

Enter the number of rows of matrix 1: 3
Enter the number of columns of matrix 1: 2
Enter the entries in a single line (separated by space): 
1 2 3 4 5 6
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


## 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [15]:
my_str = input("enter the string:- ")

words = [word.lower() for word in my_str.split()]
words.sort()

print("the sorted words are:- ")
for word in words:
    print(word)

enter the string:- My name is sharath
the sorted words are:- 
is
my
name
sharath


## 5.	Write a Python Program to Remove Punctuation From a String?

In [16]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
my_str = input("Enter a string: ")

no_punct = ""
for char in my_str:
    if char not in punctuations:
        no_punct = no_punct + char
print(no_punct)

Enter a string: Hello, world.!!!
Hello world
